spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      
  sql:
    init:
      mode: never
      
server:
  port: 5000
